// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcfsaxhmqfrgizkumdks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjZnNheGhtcWZyZ2l6a3VtZGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NTg0OTMsImV4cCI6MjA1MjAzNDQ5M30.QNtKBR2m9rn2c0cbKj4imyuXT7RuTmFQKJTxZzToTxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);